CREATE TABLE `contact_submissions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_name` text,
	`contact_person` text NOT NULL,
	`email` text NOT NULL,
	`phone` text,
	`country` text,
	`service_interest` text,
	`message` text NOT NULL,
	`compliance_consent` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `lc_applications` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_name` text NOT NULL,
	`contact_name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text NOT NULL,
	`country` text NOT NULL,
	`lc_type` text NOT NULL,
	`amount` text NOT NULL,
	`currency` text NOT NULL,
	`incoterms` text NOT NULL,
	`beneficiary_name` text,
	`issuing_bank` text,
	`expected_shipment_date` text,
	`message` text,
	`consent` integer NOT NULL,
	`applicant_address` text,
	`registration_number` text,
	`goods_description` text NOT NULL,
	`quantity` text,
	`unit` text,
	`port_of_loading` text,
	`port_of_discharge` text,
	`latest_shipment_date` text,
	`expiry_date` text NOT NULL,
	`lc_rules` text,
	`confirmation_required` integer,
	`partial_shipment_allowed` integer,
	`transshipment_allowed` integer,
	`tenor_days` integer,
	`doc_commercial_invoice` integer,
	`doc_packing_list` integer,
	`doc_transport_document` integer,
	`doc_insurance` integer,
	`doc_certificate_of_origin` integer,
	`doc_inspection_certificate` integer,
	`tax_id` text,
	`website` text,
	`shipment_mode` text NOT NULL,
	`place_of_delivery` text,
	`advising_bank_name` text,
	`advising_bank_swift` text,
	`beneficiary_bank_name` text,
	`beneficiary_bank_swift` text,
	`beneficiary_address` text,
	`tolerance_percent` integer,
	`presentation_period_days` integer,
	`additional_conditions` text,
	`contract_number` text,
	`contract_date` text,
	`proforma_invoice_number` text,
	`proforma_invoice_date` text,
	`hs_code` text,
	`country_of_origin` text,
	`price_terms` text,
	`confirming_bank_name` text,
	`confirming_bank_swift` text,
	`consignee_name` text,
	`notify_party` text,
	`transport_doc_type` text,
	`insurance_coverage_percent` integer,
	`port_of_final_destination` text,
	`charges_borne_by` text,
	`availability` text,
	`available_with` text,
	`place_of_expiry` text,
	`sblc_type` text,
	`sblc_evergreen` integer,
	`sblc_evergreen_notice_days` integer,
	`sblc_governing_law` text,
	`sblc_claim_documents` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
